### ISSUE TITLE
Add Dependencies brick which uses brightnucleus/dependencies

### ISSUE THREAD

**Issue by craigsimps** [gamajo/theme-toolkit#5]
Does it make sense to add a Dependencies brick which implements [brightnucleus/dependencies](https://github.com/brightnucleus/dependencies) and allows config based management of scripts and styles?

I have done so in reworking my Genesis Starter Theme, example: https://github.com/craigsimps/genesis-starter-theme/blob/develop/src/Dependencies.php

**Comment by GaryJones** [comment]
Yes, I'm open to that.
